substitutions:
  friendly_name: Garage Door

esphome:
  name: garage-opener

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  password:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Opener Fallback Hotspot"
    password: 

captive_portal:

switch:
    - platform: gpio
      name: opener
      pin:
        number: GPIO23
        inverted: False
      id: opener
      restore_mode: ALWAYS_OFF
      internal: true

binary_sensor:
  - platform: gpio
    name: "Open Sensor"
    pin: 
      number: GPIO26
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 50ms
    id: open_sensor
#    internal: true
  - platform: gpio
    name: "Close Sensor"
    pin: 
      number: GPIO18
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 50ms
    id: close_sensor
#    internal: true
  - platform: template
    name: "Vehicle in Garage"
    device_class: occupancy
    lambda: |-
      if (id(ultrasonic_sensor).state < 1) {
        // Vehicle is in the garage
        return true;
      } else {
        // No vehicle is in the garage
        return false;
      }
  - platform: template
    name: "Garage Door Status"
    device_class: garage_door
    lambda: |-
      if (id(close_sensor).state == false) {
        // Garage door is closed
        return true;
      } else {
        // Garage door is open
        return false;
      }

  - platform: template
    device_class: garage
    name: $friendly_name
    id: garage_door
    lambda: |-
      if (id(close_sensor).state == true) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
    open_action:
      - switch.turn_on: opener
      - delay: 0.5s
      - switch.turn_off: opener
    close_action:
      - switch.turn_on: opener
      - delay: 0.5s
      - switch.turn_off: opener      

sensor:
 # Send WiFi signal strength & uptime to HA
  - platform: ultrasonic
    trigger_pin: GPIO16
    echo_pin: GPIO17
    name: "Ultrasonic Sensor"
    update_interval: 5s
    timeout: 3m
    id: ultrasonic_sensor

  - platform: wifi_signal
    name: $friendly_name WiFi Strength
    update_interval: 60s
  - platform: uptime
    internal: true
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();
     
# Send IP Address to HA
text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address
  - platform: template
    name: $friendly_name Uptime
    id: uptime_human
    icon: mdi:clock-start
